
import type {Metadata} from 'next';
import './globals.css';
import { Toaster } from "@/components/ui/toaster";
import 'highlight.js/styles/github-dark.css'; // Import highlight.js theme

const appUrl = 'https://cabulador.vercel.app';
const ogImageUrl = `${appUrl}/og-image.png`; // You'll need to create this image
const twitterImageUrl = `${appUrl}/twitter-image.png`; // You'll need to create this image

export const metadata: Metadata = {
  title: {
    default: 'Cabulador - Seu Assistente de Estudos com IA',
    template: '%s | Cabulador',
  },
  description: 'Cabulador é um assistente de IA para estudos, desenvolvido por Saíde Omar Saíde (Quelimane, Moçambique), para ajudar estudantes com suas dúvidas e aprendizado escolar.',
  keywords: ['Cabulador', 'assistente de estudos', 'IA para estudantes', 'ajuda escolar', 'educação', 'inteligência artificial', 'Saíde Omar Saíde', 'Quelimane', 'Moçambique'],
  authors: [{ name: 'Saíde Omar Saíde', url: appUrl }],
  creator: 'Saíde Omar Saíde',
  publisher: 'Saíde Omar Saíde',
  applicationName: 'Cabulador',
  metadataBase: new URL(appUrl),
  alternates: {
    canonical: '/',
  },
  openGraph: {
    title: 'Cabulador - Seu Assistente de Estudos com IA',
    description: 'Obtenha ajuda com seus estudos com o Cabulador, uma IA desenvolvida por Saíde Omar Saíde.',
    url: appUrl,
    siteName: 'Cabulador',
    images: [
      {
        url: 'https://placehold.co/1200x630.png', // Placeholder OG image
        width: 1200,
        height: 630,
        alt: 'Cabulador - Assistente de Estudos com IA',
        // data-ai-hint for placeholder image: "AI assistant"
      },
    ],
    locale: 'pt_BR',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Cabulador - Seu Assistente de Estudos com IA',
    description: 'Seu parceiro de estudos inteligente, desenvolvido por Saíde Omar Saíde.',
    images: ['https://placehold.co/1200x600.png'], // Placeholder Twitter image. data-ai-hint: "tech education"
    // TODO: Add your Twitter handle here if you have one, e.g., creator: '@SaideOmarSaide'
  },
  viewport: {
    width: 'device-width',
    initialScale: 1,
  },
  icons: {
    // TODO: Add links to your favicon files here
    // icon: '/favicon.ico',
    // apple: '/apple-touch-icon.png',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet" />
        {/* Placeholder images with data-ai-hint for image component if used directly in head, though not typical for OG/Twitter */}
        <meta property="og:image:alt" content="Cabulador - Assistente de Estudos com IA" />
        <meta name="twitter:image:alt" content="Cabulador - Seu parceiro de estudos inteligente" />
        {/* The actual image meta tags are generated by Next.js from the metadata object */}
      </head>
      <body className="font-body antialiased">
        {children}
        <Toaster />
      </body>
    </html>
  );
}
